language: node_js
node_js:
- "10"

jobs:
  include:
    - stage: tests
      name: "Unit tests"
      script: ./runtests.sh
    - stage: build
      name: "Webpack builds umd library"
      script: npm run build

stages:
  - name: build
    if: branch = master
  - tests

notifications:
  email:
    recipients:
      - pfranco@outlook.com
    on_success: never 
    on_failure: always